import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';
import BASE_URL from '../config/api';

const Reports = () => {
  const { user } = useAuth();
  const [stats, setStats] = useState(null);
  const [cases, setCases] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState('overview');

  useEffect(() => {
    const fetchReportData = async () => {
      try {
        const [statsResponse, casesResponse] = await Promise.all([
          axios.get(BASE_URL + '/api/cases/statistics'),
          axios.get(BASE_URL + '/api/cases/management'),
        ]);

        setStats(statsResponse.data);
        setCases(casesResponse.data);
      } catch (error) {
        console.error('Error fetching report data:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchReportData();
  }, []);

  const generateBasicReport = () => {
    const reportData = {
      generatedBy: `${user.firstName} ${user.lastName} (${user.role})`,
      generatedAt: new Date().toLocaleString(),
      totalCases: stats?.totalCases || 0,
      filedCases: stats?.filedCases || 0,
      scheduledCases: stats?.scheduledCases || 0,
      completedCases: stats?.completedCases || 0,
      recentCases: cases.slice(0, 10).map(c => ({
        number: c.caseNumber,
        title: c.title,
        status: c.status,
        priority: c.priority,
        filingDate: c.filingDate
      }))
    };

    const reportText = `
DCM SYSTEM ADAPTIVE REPORT
==========================

AUTHENTICATION
--------------
Generated by : ${reportData.generatedBy}
Timestamp    : ${reportData.generatedAt}

CORE METRICS
------------
Total Records      : ${reportData.totalCases}
Filing Phase       : ${reportData.filedCases}
Hearing Schedule   : ${reportData.scheduledCases}
Final Resolutions  : ${reportData.completedCases}

LATEST RECORD SNAPSHOT
----------------------
${reportData.recentCases.map(c =>
      `[${c.number}] ${c.title}
Status: ${c.status} | Priority: ${c.priority} | Date: ${new Date(c.filingDate).toLocaleDateString()}
`).join('\n')}

--------------------------------------------------
END OF AUTOMATED SUMMARY
`;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `DCM_Report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-surface-50 dark:bg-surface-950">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto"></div>
          <p className="mt-4 text-surface-600 dark:text-surface-400 font-bold uppercase tracking-widest text-xs">Compiling Analytics...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-surface-950 p-6 md:p-8">
      <div className="max-w-7xl mx-auto space-y-8 animate-fade-in">

        {/* Header Section */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <div className="w-12 h-12 bg-amber-500 rounded-2xl flex items-center justify-center shadow-xl shadow-amber-500/20 rotate-3 transition-transform hover:rotate-0">
                <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                </svg>
              </div>
              <h1 className="text-3xl font-black text-surface-950 dark:text-white tracking-tight">Intelligence & Reports</h1>
            </div>
            <p className="text-surface-500 font-medium">Extract actionable data from your judicial workflow.</p>
          </div>

          <button
            onClick={generateBasicReport}
            className="flex items-center gap-2 px-8 py-3.5 bg-surface-950 dark:bg-surface-900 hover:bg-black dark:hover:bg-surface-800 text-white font-black rounded-2xl shadow-2xl transition-all active:scale-95 group"
          >
            <svg className="w-5 h-5 group-hover:animate-bounce" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            <span>Generate Export</span>
          </button>
        </div>

        {/* Dynamic Tab Navigation */}
        <div className="flex bg-white dark:bg-surface-900 p-1.5 rounded-[24px] border border-surface-200 dark:border-surface-800 shadow-sm w-fit">
          {[
            { id: 'overview', label: 'Overview', icon: 'M13 7h8m0 0v8m0-8l-8 8-4-4-6 6' },
            { id: 'cases', label: 'Record Registry', icon: 'M4 6h16M4 10h16M4 14h16M4 18h16' },
            { id: 'statistics', label: 'Status Metrics', icon: 'M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z' }
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setSelectedReport(tab.id)}
              className={`flex items-center gap-2 px-6 py-2.5 rounded-[18px] text-sm font-black transition-all ${selectedReport === tab.id
                ? 'bg-primary-600 text-white shadow-lg shadow-primary-500/20'
                : 'text-surface-500 hover:text-surface-900 dark:hover:text-white hover:bg-surface-50 dark:hover:bg-surface-800'}`}
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d={tab.icon} /></svg>
              <span>{tab.label}</span>
            </button>
          ))}
        </div>

        {/* Main Content Area */}
        <div className="space-y-8 min-h-[500px]">
          {selectedReport === 'overview' && (
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 animate-slide-up">
              <div className="lg:col-span-2 space-y-8">
                {/* Visual Cards */}
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                  <div className="bg-primary-600 rounded-[40px] p-8 text-white relative overflow-hidden group shadow-2xl shadow-primary-600/20">
                    <div className="relative z-10">
                      <p className="text-primary-200 text-sm font-black uppercase tracking-widest mb-2">Total Managed</p>
                      <h3 className="text-5xl font-black mb-4 tabular-nums">{stats?.totalCases || 0}</h3>
                      <div className="flex items-center gap-2">
                        <span className="p-1 px-2 rounded-lg bg-white/20 text-xs font-bold">Volume</span>
                        <span className="text-primary-200 text-xs font-medium">All database records</span>
                      </div>
                    </div>
                    <svg className="absolute -bottom-10 -right-10 w-48 h-48 text-white/10 group-hover:scale-125 transition-transform" fill="currentColor" viewBox="0 0 20 20"><path d="M2 6a2 2 0 012-2h5l2 2h5a2 2 0 012 2v6a2 2 0 01-2 2H4a2 2 0 01-2-2V6z" /></svg>
                  </div>

                  <div className="bg-emerald-600 rounded-[40px] p-8 text-white relative overflow-hidden group shadow-2xl shadow-emerald-600/20">
                    <div className="relative z-10">
                      <p className="text-emerald-200 text-sm font-black uppercase tracking-widest mb-2">Resolutions</p>
                      <h3 className="text-5xl font-black mb-4 tabular-nums">{stats?.completedCases || 0}</h3>
                      <div className="flex items-center gap-2">
                        <span className="p-1 px-2 rounded-lg bg-white/20 text-xs font-bold">Efficiency</span>
                        <span className="text-emerald-200 text-xs font-medium">Finalized cases</span>
                      </div>
                    </div>
                    <svg className="absolute -bottom-10 -right-10 w-48 h-48 text-white/10 group-hover:scale-125 transition-transform" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" /></svg>
                  </div>
                </div>

                {/* Sub-metrics */}
                <div className="grid grid-cols-2 gap-6">
                  <div className="bg-white dark:bg-surface-900 border border-surface-200 dark:border-surface-800 p-6 rounded-[32px] shadow-sm">
                    <p className="text-surface-500 text-xs font-black uppercase tracking-widest mb-1">In Filing</p>
                    <p className="text-3xl font-black text-surface-950 dark:text-white">{stats?.filedCases || 0}</p>
                  </div>
                  <div className="bg-white dark:bg-surface-900 border border-surface-200 dark:border-surface-800 p-6 rounded-[32px] shadow-sm">
                    <p className="text-surface-500 text-xs font-black uppercase tracking-widest mb-1">Scheduled</p>
                    <p className="text-3xl font-black text-surface-950 dark:text-white">{stats?.scheduledCases || 0}</p>
                  </div>
                </div>
              </div>

              <div className="bg-white dark:bg-surface-900 rounded-[40px] border border-surface-200 dark:border-surface-800 p-8 shadow-sm">
                <h3 className="text-xl font-black text-surface-950 dark:text-white mb-6">Metadata</h3>
                <div className="space-y-6">
                  <div className="flex flex-col gap-1 pb-6 border-b border-surface-100 dark:border-surface-800">
                    <span className="text-xs font-black text-surface-400 uppercase tracking-widest">Compiler</span>
                    <p className="text-base font-bold text-surface-900 dark:text-white">{user.firstName} {user.lastName}</p>
                    <span className="text-xs text-primary-600 font-bold">{user.role}</span>
                  </div>
                  <div className="flex flex-col gap-1">
                    <span className="text-xs font-black text-surface-400 uppercase tracking-widest">Extraction Date</span>
                    <p className="text-base font-bold text-surface-900 dark:text-white">{new Date().toLocaleDateString()}</p>
                    <p className="text-xs text-surface-500 font-medium">{new Date().toLocaleTimeString()}</p>
                  </div>
                  <div className="pt-6">
                    <div className="bg-surface-50 dark:bg-surface-800/50 p-4 rounded-2xl border border-dashed border-surface-200 dark:border-surface-700">
                      <p className="text-xs text-surface-600 dark:text-surface-400 font-medium">This report is an automated diagnostic snapshot of the current database state.</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          )}

          {selectedReport === 'cases' && (
            <div className="bg-white dark:bg-surface-900 rounded-[40px] border border-surface-200 dark:border-surface-800 shadow-2xl overflow-hidden animate-slide-up">
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b border-surface-100 dark:border-surface-800">
                      <th className="px-8 py-6 text-xs font-black text-surface-400 uppercase tracking-widest">LCN Reference</th>
                      <th className="px-6 py-6 text-xs font-black text-surface-400 uppercase tracking-widest">Case Directive</th>
                      <th className="px-6 py-6 text-xs font-black text-surface-400 uppercase tracking-widest text-center">Lifecycle</th>
                      <th className="px-8 py-6 text-xs font-black text-surface-400 uppercase tracking-widest text-right">Filed On</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-surface-100 dark:divide-surface-800/50">
                    {cases.slice(0, 20).map((c) => (
                      <tr key={c.id} className="group hover:bg-slate-50/50 dark:hover:bg-surface-800/30 transition-all">
                        <td className="px-8 py-5 text-sm font-black text-primary-600 dark:text-primary-400 font-mono tracking-tighter">{c.caseNumber}</td>
                        <td className="px-6 py-5">
                          <p className="text-sm font-bold text-surface-950 dark:text-white max-w-xs truncate">{c.title}</p>
                          <p className="text-[10px] font-black uppercase text-surface-400 tracking-tighter mt-0.5">{c.caseType}</p>
                        </td>
                        <td className="px-6 py-5 text-center">
                          <span className={`px-3 py-1 rounded-xl text-[9px] font-black uppercase tracking-widest border border-current opacity-70`}>{c.status}</span>
                        </td>
                        <td className="px-8 py-5 text-right">
                          <p className="text-sm font-bold text-surface-900 dark:text-white tabular-nums">{new Date(c.filingDate).toLocaleDateString()}</p>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {selectedReport === 'statistics' && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 animate-slide-up">
              <div className="bg-white dark:bg-surface-900 rounded-[40px] border border-surface-200 dark:border-surface-800 p-8 shadow-sm">
                <h3 className="text-xl font-black text-surface-950 dark:text-white mb-8">Phase Distribution</h3>
                <div className="space-y-6">
                  {[
                    { label: 'Filing Phase', val: stats?.filedCases || 0, color: 'bg-primary-500' },
                    { label: 'Judicial Review', val: cases.filter(c => c.status === 'UNDER_REVIEW').length, color: 'bg-indigo-500' },
                    { label: 'Scheduled', val: stats?.scheduledCases || 0, color: 'bg-amber-500' },
                    { label: 'Active Trial', val: cases.filter(c => c.status === 'IN_PROGRESS').length, color: 'bg-orange-500' },
                    { label: 'Resolved', val: stats?.completedCases || 0, color: 'bg-emerald-500' }
                  ].map((item) => (
                    <div key={item.label} className="space-y-2">
                      <div className="flex justify-between items-end">
                        <span className="text-xs font-black text-surface-500 uppercase tracking-widest">{item.label}</span>
                        <span className="text-sm font-bold text-surface-950 dark:text-white">{item.val} items</span>
                      </div>
                      <div className="h-3 bg-surface-100 dark:bg-surface-800 rounded-full overflow-hidden">
                        <div
                          className={`h-full ${item.color} rounded-full transition-all duration-1000`}
                          style={{ width: `${(item.val / (stats?.totalCases || 1)) * 100}%` }}
                        ></div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="bg-white dark:bg-surface-900 rounded-[40px] border border-surface-200 dark:border-surface-800 p-8 shadow-sm">
                <h3 className="text-xl font-black text-surface-950 dark:text-white mb-8">Priority Allocation</h3>
                <div className="grid grid-cols-2 gap-4">
                  {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(p => (
                    <div key={p} className="p-4 bg-slate-50 dark:bg-surface-800/50 rounded-[24px] flex items-center justify-between border border-surface-100 dark:border-surface-700">
                      <span className="text-xs font-black text-surface-400 uppercase">P{p}</span>
                      <span className="text-base font-bold text-surface-950 dark:text-white">{cases.filter(c => c.priority === p).length}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Reports;
