import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';

const Reports = () => {
  const { user } = useAuth();
  const [stats, setStats] = useState(null);
  const [cases, setCases] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState('overview');

  useEffect(() => {
    const fetchReportData = async () => {
      try {
        const [statsResponse, casesResponse] = await Promise.all([
          axios.get('http://localhost:8080/api/cases/statistics'),
          axios.get('http://localhost:8080/api/cases/management'),
        ]);

        setStats(statsResponse.data);
        setCases(casesResponse.data);
      } catch (error) {
        console.error('Error fetching report data:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchReportData();
  }, []);

  const generateBasicReport = () => {
    const reportData = {
      generatedBy: user.firstName + ' ' + user.lastName + ' (' + user.role + ')',
      generatedAt: new Date().toLocaleString(),
      totalCases: stats?.totalCases || 0,
      filedCases: stats?.filedCases || 0,
      scheduledCases: stats?.scheduledCases || 0,
      completedCases: stats?.completedCases || 0,
      recentCases: cases.slice(0, 10).map(c => ({
        number: c.caseNumber,
        title: c.title,
        status: c.status,
        priority: c.priority,
        filingDate: c.filingDate
      }))
    };

    const reportText = `
CASE MANAGEMENT SYSTEM REPORT
============================

Generated by: ${reportData.generatedBy}
Generated at: ${reportData.generatedAt}

SUMMARY STATISTICS:
------------------
Total Cases: ${reportData.totalCases}
Filed Cases: ${reportData.filedCases}
Scheduled Cases: ${reportData.scheduledCases}
Completed Cases: ${reportData.completedCases}

RECENT CASES (Last 10):
----------------------
${reportData.recentCases.map(c =>
  `Case ${c.number}: ${c.title}
   Status: ${c.status}, Priority: ${c.priority}, Filed: ${new Date(c.filingDate).toLocaleDateString()}
`).join('\n')}

This report provides basic case management statistics and recent case information.
For detailed case reports, please contact a judge or administrator.
`;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `case-report-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    window.URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600 mx-auto"></div>
          <p className="mt-4 text-lg text-gray-600 font-medium">Loading reports...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="mb-8">
          <div className="flex flex-col lg:flex-row justify-between items-start lg:items-center gap-6">
            <div className="flex items-center space-x-4">
              <div className="w-12 h-12 bg-gradient-to-r from-amber-500 to-orange-500 rounded-xl flex items-center justify-center shadow-lg">
                <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                </svg>
              </div>
              <div>
                <h1 className="text-4xl font-bold text-gray-900 tracking-tight">Reports & Analytics</h1>
                <p className="mt-1 text-lg text-gray-600 font-medium">
                  Case Management Reports and Statistics
                </p>
              </div>
            </div>
            <div className="flex items-center space-x-4">
              <button
                onClick={generateBasicReport}
                className="bg-gradient-to-r from-amber-500 to-orange-500 text-white px-6 py-3 rounded-lg hover:from-amber-600 hover:to-orange-600 transition-all duration-200 shadow-lg hover:shadow-xl flex items-center"
              >
                <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                Generate Report
              </button>
            </div>
          </div>
        </div>

        {/* Report Tabs */}
        <div className="bg-white rounded-2xl shadow-xl border border-gray-100 overflow-hidden mb-8">
          <div className="border-b border-gray-200">
            <nav className="flex">
              {[
                { id: 'overview', label: 'Overview', icon: '📊' },
                { id: 'cases', label: 'Case Details', icon: '📋', count: cases.length },
                { id: 'statistics', label: 'Statistics', icon: '📈' }
              ].map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setSelectedReport(tab.id)}
                  className={`flex items-center px-6 py-4 text-sm font-medium border-b-2 transition-colors duration-200 ${
                    selectedReport === tab.id
                      ? 'border-amber-500 text-amber-600'
                      : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                  }`}
                >
                  <span className="mr-2">{tab.icon}</span>
                  {tab.label}
                  {tab.count !== undefined && (
                    <span className="ml-2 bg-gray-100 text-gray-600 px-2 py-1 rounded-full text-xs">
                      {tab.count}
                    </span>
                  )}
                </button>
              ))}
            </nav>
          </div>

          <div className="p-6">
            {/* Overview Tab */}
            {selectedReport === 'overview' && (
              <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                  <div className="bg-gradient-to-br from-blue-50 to-blue-100 rounded-lg p-6 border border-blue-200">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-sm font-medium text-blue-600">Total Cases</p>
                        <p className="text-3xl font-bold text-blue-900">{stats?.totalCases || 0}</p>
                        <p className="text-xs text-blue-500 mt-1">All registered cases</p>
                      </div>
                      <div className="bg-blue-500 rounded-full p-3">
                        <svg className="h-6 w-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                        </svg>
                      </div>
                    </div>
                  </div>

                  <div className="bg-gradient-to-br from-emerald-50 to-emerald-100 rounded-lg p-6 border border-emerald-200">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-sm font-medium text-emerald-600">Filed Cases</p>
                        <p className="text-3xl font-bold text-emerald-900">{stats?.filedCases || 0}</p>
                        <p className="text-xs text-emerald-500 mt-1">Under processing</p>
                      </div>
                      <div className="bg-emerald-500 rounded-full p-3">
                        <svg className="h-6 w-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                      </div>
                    </div>
                  </div>

                  <div className="bg-gradient-to-br from-amber-50 to-amber-100 rounded-lg p-6 border border-amber-200">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-sm font-medium text-amber-600">Scheduled Cases</p>
                        <p className="text-3xl font-bold text-amber-900">{stats?.scheduledCases || 0}</p>
                        <p className="text-xs text-amber-500 mt-1">With hearings</p>
                      </div>
                      <div className="bg-amber-500 rounded-full p-3">
                        <svg className="h-6 w-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                        </svg>
                      </div>
                    </div>
                  </div>

                  <div className="bg-gradient-to-br from-cyan-50 to-cyan-100 rounded-lg p-6 border border-cyan-200">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-sm font-medium text-cyan-600">Completed Cases</p>
                        <p className="text-3xl font-bold text-cyan-900">{stats?.completedCases || 0}</p>
                        <p className="text-xs text-cyan-500 mt-1">Successfully resolved</p>
                      </div>
                      <div className="bg-cyan-500 rounded-full p-3">
                        <svg className="h-6 w-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 3v4M3 5h4M6 17v4m-2-2h4m5-16l2.286 6.857L21 12l-5.714 2.143L13 21l-2.286-6.857L5 12l5.714-2.143L13 3z" />
                        </svg>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="bg-gradient-to-r from-amber-50 to-orange-50 rounded-lg p-6 border border-amber-200">
                  <h3 className="text-lg font-semibold text-amber-900 mb-4 flex items-center">
                    <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
                    </svg>
                    Report Information
                  </h3>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                      <p className="text-sm text-amber-700"><strong>Report Generated By:</strong></p>
                      <p className="text-sm text-amber-900">{user.firstName} {user.lastName} ({user.role})</p>
                    </div>
                    <div>
                      <p className="text-sm text-amber-700"><strong>Generated At:</strong></p>
                      <p className="text-sm text-amber-900">{new Date().toLocaleString()}</p>
                    </div>
                  </div>
                  <div className="mt-4 p-4 bg-white rounded-lg border border-amber-200">
                    <p className="text-sm text-amber-800">
                      <strong>Note:</strong> This is a basic clerk-level report. For detailed case analytics,
                      judge-specific reports, or PDF exports, please contact a judge or administrator.
                    </p>
                  </div>
                </div>
              </div>
            )}

            {/* Cases Tab */}
            {selectedReport === 'cases' && (
              <div className="space-y-6">
                <div className="overflow-x-auto">
                  <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gray-50">
                      <tr>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Case Number
                        </th>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Title
                        </th>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Status
                        </th>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Priority
                        </th>
                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                          Filing Date
                        </th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {cases.slice(0, 50).map((caseItem) => (
                        <tr key={caseItem.id} className="hover:bg-gray-50">
                          <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                            {caseItem.caseNumber}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 truncate max-w-xs">
                            {caseItem.title}
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap">
                            <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                              caseItem.status === 'COMPLETED' ? 'bg-emerald-100 text-emerald-800' :
                              caseItem.status === 'IN_PROGRESS' ? 'bg-blue-100 text-blue-800' :
                              caseItem.status === 'SCHEDULED' ? 'bg-amber-100 text-amber-800' :
                              'bg-gray-100 text-gray-800'
                            }`}>
                              {caseItem.status.replace('_', ' ')}
                            </span>
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                            {caseItem.priority}/10
                          </td>
                          <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                            {new Date(caseItem.filingDate).toLocaleDateString()}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
                {cases.length > 50 && (
                  <div className="text-center text-sm text-gray-500 py-4">
                    Showing first 50 cases. Full reports available to judges and administrators.
                  </div>
                )}
              </div>
            )}

            {/* Statistics Tab */}
            {selectedReport === 'statistics' && (
              <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="bg-white rounded-lg border border-gray-200 p-6">
                    <h3 className="text-lg font-semibold text-gray-900 mb-4">Case Status Distribution</h3>
                    <div className="space-y-3">
                      <div className="flex justify-between items-center">
                        <span className="text-sm text-gray-600">Filed</span>
                        <span className="text-sm font-medium text-gray-900">{stats?.filedCases || 0}</span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="text-sm text-gray-600">Under Review</span>
                        <span className="text-sm font-medium text-gray-900">
                          {cases.filter(c => c.status === 'UNDER_REVIEW').length}
                        </span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="text-sm text-gray-600">Scheduled</span>
                        <span className="text-sm font-medium text-gray-900">{stats?.scheduledCases || 0}</span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="text-sm text-gray-600">In Progress</span>
                        <span className="text-sm font-medium text-gray-900">
                          {cases.filter(c => c.status === 'IN_PROGRESS').length}
                        </span>
                      </div>
                      <div className="flex justify-between items-center">
                        <span className="text-sm text-gray-600">Completed</span>
                        <span className="text-sm font-medium text-gray-900">{stats?.completedCases || 0}</span>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white rounded-lg border border-gray-200 p-6">
                    <h3 className="text-lg font-semibold text-gray-900 mb-4">Priority Distribution</h3>
                    <div className="space-y-3">
                      {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map(priority => (
                        <div key={priority} className="flex justify-between items-center">
                          <span className="text-sm text-gray-600">Priority {priority}</span>
                          <span className="text-sm font-medium text-gray-900">
                            {cases.filter(c => c.priority === priority).length}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Reports;
